spring.application.name=pcfactory

#puerto springboot:
server.port=8080

#nombre base de datos
spring.datasource.name=pcfactory

#va hacia la instancia EC2 mediante su IP Pública (es dinámica por cierto).
spring.datasource.url=jdbc:mysql://3.229.142.22:3306/pcfactory

spring.datasource.username=root
spring.datasource.password=zacky

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create